#spring.application.name=consultorioMedico
                                                # De ser necesario tambien cambiar este puerto
spring.datasource.url=jdbc:mysql://localhost:3306/consultorio
spring.datasource.username=root
spring.datasource.password=
#server.port = 8080
#hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto =update
spring.jpa.show-sql = true
jwt.secret-key=+T+oFFUUml+UVhByeSzZmpqO3O9Vk78jYYcBTPkXkoyNcubm3wos7pxttUhVxkpgxnf/rUrgsinuZqYrptO9tjY3XGJim6KJLRlm8S6yywAzmFVdLCgRqBMkYfgzrINjO7seLzsnbiESlB0INh6RMu40Pv8nyLQVXKagNGaDwingojD0jf7zWgXEwCwJK9HvS5KOgjoWQbGrjfw4pP1FSN6IHtJIMdmf3HvzoDVPcyPejc/6SH4xqyJV7GC9qy3hV9EDa8m9OFmCKy8wLdcyKelpLvRpeY1lL/MFrjVcJV+nSR8eysFtzy6LVbXrni5wkY8x5UykzXZ1lMWcJYJXO2tvPyraX+YB0xSfXCsCwi0=

